Repository ArkEcosystem/laravel-fortify, pull requests merged in 2021-03, with the labels that each got.

#78 fix: use single column for passphrase validation on registration page
  resources/views/auth/register-form.blade.php
  resources/views/components/password-rules.blade.php
Labels: Complexity: Low, Type: Bugfix

#80 chore: remove unnecessary notifications settings link
  resources/lang/en/auth.php
  resources/views/auth/register-form.blade.php
  tests/Components/RegisterFormTest.php
Labels: Complexity: Low, Type: Task

#81 chore: improve components for e2e tests
  resources/views/profile/delete-user-form.blade.php
  resources/views/profile/update-password-form.blade.php
Labels: Complexity: Low, Status: Needs Review, Type: Task

#84 feat: store the profile photos with responsive images
  src/Components/UpdateProfilePhotoForm.php
  src/Models/Concerns/HasPhoto.php
  tests/Components/UpdateProfilePhotoFormTest.php
  tests/Models/Concerns/HasPhotoTest.php
Labels: Complexity: Low, Type: Feature

#85 fix: ignore 2fa field text when submitting recovery code
  resources/views/auth/two-factor-challenge.blade.php
Labels: Complexity: Low, Type: Bugfix

#87 refactor: reset password rules on update
  resources/views/components/password-rules.blade.php
  resources/views/profile/update-password-form.blade.php
  src/Components/Concerns/ValidatesPassword.php
  src/Components/UpdatePasswordForm.php
  tests/Components/UpdatePasswordFormTest.php
Labels: Complexity: Medium, Type: Refactor

#86 fix: update button alignment to match design
  resources/views/auth/two-factor-challenge.blade.php
Labels: Complexity: Low, Type: Task

#89 chore: update 2fa wording
  resources/lang/en/pages.php
Labels: Complexity: Low, Type: Task

#88 fix: 2fa recovery code form validation
  resources/views/auth/two-factor-challenge.blade.php
  src/Responses/FailedTwoFactorLoginResponse.php
  tests/Responses/FailedTwoFactorLoginResponseTest.php
Labels: Complexity: Low, Type: Bugfix

#90 feat: separate two-factor and recovery code forms
  resources/views/auth/two-factor-challenge.blade.php
Labels: Complexity: Medium, Type: Feature

#94 chore: add success message when the job for exporting the user data starts
  resources/lang/en/pages.php
  resources/views/profile/export-user-data.blade.php
  src/Components/ExportUserData.php
  tests/Components/ExportUserDataTest.php
Labels: Complexity: Low, Type: Task

#95 refactor: remove verified page
  resources/lang/en/auth.php
  resources/views/auth/verified.blade.php
Labels: Complexity: Low, Type: Refactor

#96 chore: remove verify images
  README.md
  resources/images/auth/verified-email.svg
  resources/images/auth/verify-email.svg
Labels: Complexity: Low, Type: Task

#97 refactor: update verify page design
  composer.lock
  resources/lang/en/auth.php
  resources/views/auth/verify-email.blade.php
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#101 feat: disable gdpr export button while busy
  resources/views/profile/export-user-data.blade.php
Labels: Complexity: Low, Type: Feature

#100 fix: handle null values on the password validator
  src/Rules/Password.php
  tests/Rules/PasswordTest.php
Labels: Complexity: Low, Type: Bugfix

#98 refactor: move newsletter subscription from ark.io
  .editorconfig
  composer.json
  composer.lock
  config/newsletter.php
  resources/lang/en/messages.php
  resources/views/newsletter/footer-subscription-form.blade.php
  src/Actions/SubscribeToNewsletter.php
  src/Components/FooterEmailSubscriptionForm.php
  src/FortifyServiceProvider.php
  tests/Actions/SubscribeToNewsletterTest.php
  tests/Components/FooterEmailSubscriptionFormTest.php
  tests/TestCase.php
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#102 fix: add null check before validating password
  src/Components/Concerns/ValidatesPassword.php
  tests/Components/UpdatePasswordFormTest.php
Labels: Complexity: Low, Type: Bugfix

#103 fix: typo in class name that prevents the correct font from loading
  resources/lang/en/auth.php
Labels: Complexity: Low, Type: Bugfix

#104 chore: improve newsletter subscription form
  resources/views/newsletter/footer-subscription-form.blade.php
Labels: Complexity: Low, Type: Task

#108 fix: reset password alert
  resources/views/auth/login.blade.php
Labels: Complexity: Low, Type: Bugfix
